language: java
sudo: required
dist: trusty
services:
   - docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2/repository

before_install:
  - docker -v
# https://github.com/travis-ci/travis-ci/issues/8408
# Also interferes with platform-tooling-support-tests expectations
  - unset _JAVA_OPTIONS

install:
  - echo "Don't let Travis CI execute './gradlew assemble' by default"

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - mvn -nsu clean verify compile install
