language: java
sudo: required
dist: trusty
services:
   - docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2/repository

before_install:
  - docker -v

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - docker-compose -f docker-compose.yml up -d
  - docker-compose -f docker-compose.yml ps
  - mvn -nsu clean verify compile install
