elasticsearch_master:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
      command: "elasticsearch -Ecluster.name=elasticsearch -Enode.master=true"
      environment:
         - ES_HEAP_SIZE=512m
      ports:
        - "9200:9200"
        - "9300:9300"